export enum Action {
  DRINKING = 'DRINKING',
  EATING = 'EATING',
  EXPLORING = 'EXPLORING',
  FLEEING = 'FLEEING',
  HIDING = 'HIDING',
  LOOKING_FOR_FOOD = 'LOOKING_FOR_FOOD',
  LOOKING_FOR_MATE = 'LOOKING_FOR_MATE',
  LOOKING_FOR_WATER = 'LOOKING_FOR_WATER',
  MATING = 'MATING',
  NEUTRAL = 'NEUTRAL',
  RUNNING = 'RUNNING',

}