export enum Condition {
  DEAD = 'DEAD',
  DYING = 'DYING',
  FULL_STOMACH = 'FULL STOMACH',
  HUNGRY = 'HUNGRY',
  HYDRATED = 'HYDRATED',
  INJURED = 'INJURED',
  STARVING = 'STARVING',
  THIRSTY = 'THIRSTY',
  TIRED = 'TIRED',
  WEAK = 'WEAK',
}